version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8u181-jdk
    working_directory: ~/repo
    environment:
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle.kts" }}
            - v1-dependencies-
      - run: ./gradlew compileTestKotlin
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle.kts" }}
      - run:
          command: ./gradlew build
      - store_artifacts:
          path: ./build/reports/tests
          destination: test-reports
      - store_test_results:
          path: ./build/test-results
  test_integration:
    docker:
      - image: circleci/openjdk:8u181-jdk
    resource_class: large
    working_directory: ~/repo
    environment:
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle.kts" }}
            - v1-dependencies-
      - run: ./gradlew compileTestKotlin
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle.kts" }}
      - run:
          command: |
              echo ${JIRA_LICENSE} > jira-license.txt
              USER=$CIRCLE_BUILD_URL ./gradlew testIntegration
          no_output_timeout: 70m
      - store_artifacts:
          path: ./build/reports/tests
          destination: test-reports
      - store_test_results:
          path: ./build/test-results
workflows:
  version: 2
  quick:
    jobs:
      - build
  wide:
    jobs:
      - trigger:
          type: approval
      - test_integration:
          requires:
            - trigger
  regular:
    triggers:
      - schedule:
          cron: "0 0 * * 0"
          filters:
            branches:
              only:
                - master
    jobs:
      - test_integration

